### ISSUE TITLE
Offline tool does not work offline

### ISSUE THREAD

**Issue by xfactorial927** [developersharif/bgremover-app#11]
**Describe the bug**
When I attempt to use the Remove Background feature of the BG Remover program, it does not work and an error message pops up. I am using version 2.0.0 of the BG Remover and have downloaded the model.

**To Reproduce**
1. Disable your internet connection, either by unplugging your ethernet cable or disabling wifi.
2. Open the BG Remover program.
3. Open an image.
4. Select "Remove Background"
5. An error will occur stating "Failed to process image: HTTPSConnectionPool(host='github.com', port=443): Max retries exceeded with url: /danielgatis/rembg/releases/download/v0.0.0/u2net.onnx (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000028F1B941C90>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"

**Expected behavior**
As the tool is advertised as "Offline," I would expect to be able to use it offline. I don't know if this was an error in the way it was setup or if the owner just meant "offline" to mean "not within a web browser," but the tool does not work offline. I was looking for a background-removing tool I could use on the go with my laptop when I do not have an internet connection but have taken new photos.

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro version 22H2

**Additional context**
A similar error with a different error code and explanation occurs when I am connected to the internet but block BG Remover's internet access via Windows Firewall.

**Comment by developersharif** [comment]
Thank you for reaching out regarding the issue with the offline bgremover repository. It seems that the offline toot is not working for you. In order to resolve this, please follow the steps below:

1. Make sure you have **fully downloaded the model file**. The offline functionality requires the complete model file to be available on your system.

2. Create a new file named "**model.bat**" in your bgremover repository.

3. Open the link provided below to access the code for the "windows-model-download.bat" file:
   [Link to "windows-model-download.bat"](https://github.com/developersharif/bgremover-app/blob/main/windows-model-download.bat)

4. Copy the code from the "windows-model-download.bat" file and paste it into your newly created "model.bat" file.
5. Run the bat file to complete the download process. 
By following these steps, you should be able to ensure that the required model file is downloaded and available for the offline functionality to work properly.

If you continue to encounter any issues or require further assistance, please feel free to let us know. We're here to help!
