### ISSUE TITLE
Problem saving jpg

### ISSUE THREAD

**Issue by ZarinNegah** [developersharif/bgremover-app#13]
Hello
Good time

In version 2, after removing the background or whitening the background of the image
When we want to save in jpg format, we come across the errore in the attachment

where is the problem from?
![-2147483648_-213681](https://github.com/developersharif/bgremover-app/assets/39865873/955c7142-e08b-48d9-8cd8-e082ea20d4d1)

**Comment by ZarinNegah** [comment]
please check issue

**Comment by developersharif** [comment]
> please check issue
Thank you for reaching out to us with this issue. I appreciate your feedback and understand the problem you're experiencing. As a single developer, I need some time to investigate and resolve this issue. I'll prioritize this and work on a solution as asap.

**Comment by ZarinNegah** [comment]
Hello
Thank you for checking
We are waiting for your good news

**Comment by developersharif** [comment]
> Hello Thank you for checking We are waiting for your good news

Thank you for your clarification. I understand the issue now. The error you're encountering, 'Cannot write mode RGBA as JPEG,' is because JPG format doesn't support transparency (alpha channel) by default. JPG is a lossy compression format and is designed for images with a solid, opaque background.

To save a transparent background, you should consider using a format that supports transparency, such as PNG. If you'd like to keep the quality of the image and retain the transparency, I recommend saving it as a PNG instead of JPG.

**Comment by ZarinNegah** [comment]
Hello
Good time
We need images with colored background and png format is not usable for us
And also only jpg format can be used for our work
Solutions are available on the Internet
Please upgrade

https://stackoverflow.com/questions/48206051/image-conversion-cannot-write-mode-rgba-as-jpeg

https://stackoverflow.com/questions/52497433/cannot-write-mode-rgba-as-jpeg-how-to-resolve-this-error-without-converting-imag

https://github.com/python-pillow/Pillow/issues/2609
