### ISSUE TITLE
Opened image size distorted.

### ISSUE THREAD

**Issue by ileanre** [developersharif/bgremover-app#8]
**Describe the bug**
Image that open with open image button is always distorted. Saved image continue to be distorted.

**To Reproduce**
Open image via button "Open image" and File/open image

**Expected behavior**
Image open normal size

**Screenshots**
I use the windows stable version non installer.
![image](https://user-images.githubusercontent.com/128200745/228424394-4ccef5d7-c678-4534-a431-b384b8ed267e.png)

**Comment by developersharif** [comment]
> **Describe the bug** Image that open with open image button is always distorted. Saved image continue to be distorted.
> 
> **To Reproduce** Open image via button "Open image" and File/open image
> 
> **Expected behavior** Image open normal size
> 
> **Screenshots** I use the windows stable version non installer. ![image](https://user-images.githubusercontent.com/128200745/228424394-4ccef5d7-c678-4534-a431-b384b8ed267e.png)

Thank you for bringing this issue to our attention. We apologize for any inconvenience this may have caused you.

We have noted the problem you described with the image distortion when opening an image via the "Open Image" button or File/open image. Our development team will investigate this issue and work to find a solution as soon as possible.

Regarding your suggestion to use version 2.0 instead of version 1.0, we appreciate your input. Version 2.0 has some significant improvements and we encourage you to try it out. Additionally, using full-screen mode may also improve the results.

We will keep you updated on the progress of our investigation into the image distortion issue. If you have any further questions or concerns, please don't hesitate to reach out.

**Comment by ileanre** [comment]
Thanks for super fast reply. I just retry with version 2. Problem not exist in version 2. Noted, full screen improve the result alot. FYI Here's the result of BG remove v 2
![image](https://user-images.githubusercontent.com/128200745/228425635-629ee64d-68a5-48c6-b8e0-4bcca0340960.png)

Here's another result.
![image](https://user-images.githubusercontent.com/128200745/228425832-a3780109-ff35-4765-b052-341a010831e0.png)

Trained model downloaded twice (just to make sure)
